### ISSUE TITLE
global config file

### ISSUE THREAD

**Issue by hugojosefson** [hugojosefson/incus-app-container#3]
## Motivation

The user shouldn't have to specify all options on command-line.

## Implementation

Load options from `/etc/defaults/incus-app-container`. See https://www.baeldung.com/linux/config-files.

Actual command-line options still override any config file.

### Config file format

- [TOML](https://toml.io/)
- It specifies options.
- Each command in the script, has a specific table in the config file.
- Under a command's table, you specify options for it.
- The root table is for any options before the command. (No such options exist yet.)

#### Example

```toml
[create]
apps-dir = "/mnt/apps"
disk-size = "10GiB"
start = true
ssh-key = "gh:hugojosefson"
```
